# Schema for the configuration files of the Drupalsky module.
drupalsky.settings:
  type: config_object
  label: 'Drupalsky settings'
  mapping:
    example:
      type: string
      label: 'Example'
